### PR TITLE
ARKit image detection & Vertical Plane Detection

### PR DESCRIPTION
**Pull request by macrozone**
## Image detection 

Usage:

```
<ARKit 
  detectionImages={[{ resourceGroupName: 'DetectionImages' }]}
  onAnchorDetected={onAnchorUpdated}
  onAnchorUpdated={onAnchorUpdated}
  onAnchorRemoved={onAnchorRemoved}
/>

```

- `detectionImages` is an array of objects. Currently only images from assets are possible, but in future, we also want to enable images from filesystem, remote, etc. 
- to add an image to detect to xcode, see https://developer.apple.com/documentation/arkit/arreferenceimage?language=objc
- see also https://developer.apple.com/documentation/arkit/recognizing_images_in_an_ar_experience?language=objc for best practises
- `onAnchorDetected`, `onAnchorUpdated` and `onAnchorRemoved` is the more generic version of `onPlaneDetected`, etc. onAnchorDetected will notfiy about every anchor (plane and image currently).
- these callbacks passes an object with the same properties as in the `onPlane`-callbacks (position, positionAbsolute, eulerAngles, id)
- the object has a new `type`-property that specifies the type of the anchor (currently `plane` and `image`)
- depending on the type, there are additional properties on the anchor
- If you specify the `onPlane`-versions, `onAnchor` won't notify about planes atm. but i will review this decision. I am unsure whether we should have a `onXXXAnchor...` for every anchor type or just one generic `onAnchor`-callback for every anchor type (i favour the later).
- `onPlaneUpdate` has been renamed to `onPlaneUpdated` (more consistent)

## Vertical plane detection

Usage:

```
<ARKit 
  planeDetection={ARKit.ARPlaneDetection.HorizontalVertical}
/>

```

Will notify about vertical planes as well in `onPlaneDetected`. You can distinguish with `planeAnchor.alignment === ARKit.ARPlaneAnchorAlignment.Vertical`

### CODE REVIEW

**Comment by elderbas** [comment]
I'm on `"react-native-arkit": "0.9.0-beta.3"`.
Have a fresh `create-react-native` install, followed the steps for manual install. and trying to get a basic asset showing on the screen

and I'm getting `undefined is not an object (evaluating 'ARKitManager.ARPlaneDetection')`

image

**Comment by macrozone** [comment]
@elderbas it's `ARKit.ARPlaneDetection`. `ARKitManager` is used internally. Was this mentioned somewhere in the readme? maybe i did a mistake

**Comment by elderbas** [comment]
This is the only mention of `ARKit.ARPlaneDetection` in the docs

image

Also, FYI, if I don't put a value for `planeDetection` prop, to let it go to default, I still get the same error.

**Comment by macrozone** [comment]
@elderbas I fixed the typo in the example in the Readme. 

I also tried to not give a value for planeDetection and it worked. I am not sure what went wrong, can you try to reproduce it and file an issue?

**Comment by JackSoby** [comment]
@macrozone Any update when you would be able to use images from an external resource like a s3 bucket?

**Pull request merged**
